//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMIS.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMIS.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra vui lòng liên hệ MISA.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đáp án đúng không hợp lệ.
        /// </summary>
        public static string ExcelAnswerTrueInvalid {
            get {
                return ResourceManager.GetString("ExcelAnswerTrueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn đáp án đúng cho câu hỏi.
        /// </summary>
        public static string ExcelAnswerTrueNull {
            get {
                return ResourceManager.GetString("ExcelAnswerTrueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu nội dung câu hỏi.
        /// </summary>
        public static string ExcelContenNull {
            get {
                return ResourceManager.GetString("ExcelContenNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng đáp án đúng không hợp lệ.
        /// </summary>
        public static string ExcelNumAnswerInvalid {
            get {
                return ResourceManager.GetString("ExcelNumAnswerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu loại câu hỏi .
        /// </summary>
        public static string ExcelTypeNull {
            get {
                return ResourceManager.GetString("ExcelTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung đáp án không được để trống.
        /// </summary>
        public static string InvalidAnswerContent {
            get {
                return ResourceManager.GetString("InvalidAnswerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái đáp án không hợp lệ.
        /// </summary>
        public static string InvalidAnswerState {
            get {
                return ResourceManager.GetString("InvalidAnswerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu vào không hợp lệ.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bài tập không được bỏ trống.
        /// </summary>
        public static string InvalidExerciseName {
            get {
                return ResourceManager.GetString("InvalidExerciseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái bài tập không hợp lệ.
        /// </summary>
        public static string InvalidExerciseState {
            get {
                return ResourceManager.GetString("InvalidExerciseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id khối không hợp lệ.
        /// </summary>
        public static string InvalidGradeID {
            get {
                return ResourceManager.GetString("InvalidGradeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên câu hỏi không được bỏ trống.
        /// </summary>
        public static string InvalidQuestionName {
            get {
                return ResourceManager.GetString("InvalidQuestionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thứ tự câu hỏi không được để trống.
        /// </summary>
        public static string InvalidQuestionNumber {
            get {
                return ResourceManager.GetString("InvalidQuestionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại câu hỏi không hợp lệ.
        /// </summary>
        public static string InvalidQuestionType {
            get {
                return ResourceManager.GetString("InvalidQuestionType", resourceCulture);
            }
        }
    }
}
