//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB02.EMIS.API.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WEB02.EMIS.API.Common.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái đáp án không đúng.
        /// </summary>
        public static string AnswerStatus {
            get {
                return ResourceManager.GetString("AnswerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ô nhập liệu không được để trống.
        /// </summary>
        public static string ErrorCellRequire {
            get {
                return ResourceManager.GetString("ErrorCellRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi file ảnh.
        /// </summary>
        public static string ErrorFileImage {
            get {
                return ResourceManager.GetString("ErrorFileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu không thành công.
        /// </summary>
        public static string ExceptionDelete {
            get {
                return ResourceManager.GetString("ExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu không thành công.
        /// </summary>
        public static string ExceptionInsert {
            get {
                return ResourceManager.GetString("ExceptionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu không thành công.
        /// </summary>
        public static string ExceptionUpdate {
            get {
                return ResourceManager.GetString("ExceptionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái bài tập không đúng.
        /// </summary>
        public static string ExerciseStatus {
            get {
                return ResourceManager.GetString("ExerciseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đáp án phải có nội dung hoặc hình ảnh.
        /// </summary>
        public static string InvalidAnswerContent {
            get {
                return ResourceManager.GetString("InvalidAnswerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khối lớp không được để trống.
        /// </summary>
        public static string InvalidGrade {
            get {
                return ResourceManager.GetString("InvalidGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi phải có nội dung hoặc hình ảnh.
        /// </summary>
        public static string InvalidQuestionContent {
            get {
                return ResourceManager.GetString("InvalidQuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn học không được để trống.
        /// </summary>
        public static string InvalidSubject {
            get {
                return ResourceManager.GetString("InvalidSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đạt giới hạn đáp án.
        /// </summary>
        public static string LimitAnswer {
            get {
                return ResourceManager.GetString("LimitAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi phải có đáp án đúng.
        /// </summary>
        public static string NotAnswerCorrect {
            get {
                return ResourceManager.GetString("NotAnswerCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        public static string NullData {
            get {
                return ResourceManager.GetString("NullData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại câu hỏi không đúng.
        /// </summary>
        public static string TypeQuestion {
            get {
                return ResourceManager.GetString("TypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự luận.
        /// </summary>
        public static string TypeQuestion_Essay {
            get {
                return ResourceManager.GetString("TypeQuestion_Essay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền vào chỗ trống.
        /// </summary>
        public static string TypeQuestion_Fill {
            get {
                return ResourceManager.GetString("TypeQuestion_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi nhóm.
        /// </summary>
        public static string TypeQuestion_Group {
            get {
                return ResourceManager.GetString("TypeQuestion_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn đáp án.
        /// </summary>
        public static string TypeQuestion_Select {
            get {
                return ResourceManager.GetString("TypeQuestion_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đúng sai.
        /// </summary>
        public static string TypeQuestion_YesOrNo {
            get {
                return ResourceManager.GetString("TypeQuestion_YesOrNo", resourceCulture);
            }
        }
    }
}
